name: Dependency Updates

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  dependency-update:
    name: Check and Update Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Dependency Bot
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDENCY_BOT_TOKEN }}
          GITHUB_APP_ID: ${{ secrets.DEPENDENCY_BOT_APP_ID }}
          GITHUB_PRIVATE_KEY: ${{ secrets.DEPENDENCY_BOT_PRIVATE_KEY }}
          GITHUB_INSTALLATION_ID: ${{ secrets.DEPENDENCY_BOT_INSTALLATION_ID }}
        run: node dependency-bot.js

      - name: Output debug info if failed
        if: ${{ failure() }}
        run: |
          echo "Node.js version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Package.json content:"
          cat package.json
